#!/bin/bash

git add .

echo -e "Would You Like To Pull Online Changes Locally? [Y/N]:"

read -e -r answer

if [[ "$answer" == "Y" ]]
then
	git pull
fi

echo -e "Enter Your Commit Message Without Qoutes: \c"

read -e  -r message

git commit -m $"$message"

git push
